name: CI/CD for WordPress Theme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Ajout du déclencheur manuel

jobs:
  validate-code:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Installer PHP et Composer
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer

    # Installer les dépendances PHP
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Vérifier la qualité du code avec PHP_CodeSniffer
    - name: Run PHP_CodeSniffer
      run: ./vendor/bin/phpcs --standard=WordPress ./

    # Vérifier le code avec PHPStan
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse

    # Vérifier le code avec Psalm
    - name: Run Psalm
      run: ./vendor/bin/psalm

    # Vérifier le code avec PHP Mess Detector
    - name: Run PHPMD
      run: ./vendor/bin/phpmd ./ text cleancode,codesize,controversial,design,naming,unusedcode

  build:
    runs-on: ubuntu-latest
    needs: validate-code

    steps:
    # Vérifier le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurer Node.js pour utiliser npm
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Installer les dépendances npm
    - name: Install dependencies
      run: npm install

    # Compiler les assets avec npm
    - name: Build assets
      run: npm run build:css

  deploy:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Déployer les fichiers via FTP ou autre méthode
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Répertoire local à déployer
          server-dir: /path/to/remote/theme-directory # Répertoire distant
